name: CI

on:
  push:
    branches: [ main, notebook ]
  pull_request:
    branches: [ main, notebook ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r notebooks/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src/ tests/

      - name: Check code formatting with black
        run: |
          black --check src/ tests/

      - name: Run tests with pytest
        run: |
          pytest tests/

      - name: Check Jupyter notebooks (optional)
        run: |
          pip install nbconvert
          jupyter nbconvert --execute --to notebook --inplace notebooks/bank_reviews_analysis.ipynb
        continue-on-error: true 